### ISSUE TITLE
Household: Selecting any response to question causes app to return to Household summary display.

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#10]
1. Create or open a new Household question set.
2. Complete the question set.
3. From the Household summary display, open the same question set.
4. Scroll down to "Index case: Overnight Travel outside Zanzibar within past year"
5. Select any option [Yes | No | Unknown | Not applicable]

Expected: If Yes, app will ask user to provide location information. Otherwise, app will not ask for location information.

Actual: App returns to Household summary display.

![image](https://user-images.githubusercontent.com/329768/27753819-3c830788-5db5-11e7-88f4-0c868315fe2f.png)

**Comment by scloo** [comment]
Unable to reproduce the issue. Must have been fixed together with the previous other issues.
