### ISSUE TITLE
Default sorting of records on home display

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#13]
The default sort order of records on the home display appears to be by the Date field, with the most recent record at the top. I believe this is correct, but I noticed two issues that looked strange to me.

I completed 3 new case notifications. The app created the matching incomplete Facility question sets. 

**Expected:** Each new incomplete Facility question set will be listed immediately above its matching Case Notification, since they were created in that order. 

**Actual:** The 3 new incomplete Facility records are listed first, followed by the 3 new completed Case Notifications.

I note that some question sets have date/time stamps, while others appear to have dates only.  Why don't they all have date/time stamps?

![image](https://user-images.githubusercontent.com/329768/27886140-c80522cc-61a8-11e7-9f81-a3485f1dacae.png)

**Comment by scloo** [comment]
Fixed the timestamp issue . And that should fix the sorting order now since previously for some of the cases, they have the date as YYYY-MM-DD instead of a time stamp.
