### ISSUE TITLE
Head of Household not transferred from Facility to Household record

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#19]
When a Household record is created, Head of Household name is not transferred from the matching Facility record.

**Comment by gmcressman** [comment]
Same issue with the following field: Contact Mobile # (patient/relative)

**Comment by scloo** [comment]
@mikeymckay 
I noticed the inconsistency in the naming of the attributes for the Facility questions.
in some doc it is spelled as ContactMobilepatientrelative, while in others it is spelled ContactMobilePatientRelative. Likewise for 'HeadOfHouseholdName' and 'HeadofHouseholdName'.

I think causes issue in createHousehold() in the plugin Case. And the Head of Household Name and the Contact Mobile Patient Relative are not saved to the Household question.

**Comment by scloo** [comment]
@mikeymckay I suspect that the Form2jsPlugins that you introduced in the plugin, converts the attribute names to camelize  form that is inconsistent with previous Facility question docs that do not use camelize form in the attribute names.
And I suspect that the other questions are also affected similarly.

In Case.coffee - createHousehold(), you have 
HeadofHouseholdName: @Facility.HeadofHouseholdName
ContactMobilepatientrelative: @Facility.ContactMobilepatientrelative

Attribute @Facility.HeadofHouseholdName does longer exist as you have already camelize to @Facility.HeadOfHouseholdName when saving the completed Facility question.

**Comment by mikeymckay** [comment]
Yes - the previous version used a simple hand-made camelcase, which
wouldn't capitalize every word. The problem was that it also created
invalid couchdb ids if the question name had a strange character in it. So
in order to fix this Coconut Mobile now uses slugify to create safe names.
In order to support backwards compatibility with Coconut Surveillance I
have added a filter to form2js (via a plugin) which attempted to get the
attributes into the same format as was used in the original Coconut
Surveillance. Seems like this is broken in a few places. I think that the
best thing to do will be to update the plugin to handle these cases.

**Comment by scloo** [comment]
@mikeymckay I see that you have made changes (Nov 25 in plugin codes) that took care of the camel case to HeadOfHouseHoldName. That solves the issue in Facility results view that was missing the Head of House Name. However in the Household result view, the data is still missing for Head Of Household Name and Total Number of Residents in the Household. Does this have anything to do with the fact that in the Case doc, the attributes are still in the old format "HeadofHouseholdName"?
![Screen Shot 2017-12-05 at 4.18.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571a5f9b500b7b0e00eca657/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216454f66b7191a37cf113234f5e5c5ecc3c4a4356bcbbd671f3e57862804e0eead06a0a71c33a17ffee8a18ed52e8208b4d86e0b98349d2f42f67b6d5db1063474f4dcbed5727a19e41c95df749e44d5da3123461e0712431.png)

**Comment by gmcressman** [comment]
Tested. Fixed. @scloo - Does the problem in your Dec 5 comment on this issue still exist?
