### ISSUE TITLE
Household summary display: Does not list values for Head of Household or Number of Residents...

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#21]
Summary display table does not show values for the following fields:

Head of Household
Total Number of Residents in the Household

![screen shot 2017-11-17 at 11 59 18 am](https://user-images.githubusercontent.com/329768/32959234-ff92a4da-cb8e-11e7-8949-f1593c6eff59.png)

**Comment by scloo** [comment]
I think issue # 19,20,21 are all related. If we can resolve 19, I think it will also resolve the other 2.

**Comment by gmcressman** [comment]
Tested. Fixed.
