### ISSUE TITLE
Household Member summary: Head of Household not displayed

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#23]
The Head of Household is not displayed on the Household Member summary.

![screen shot 2017-11-17 at 12 05 02 pm](https://user-images.githubusercontent.com/329768/32959498-c9047032-cb8f-11e7-82b5-ebd95e36fb07.png)

**Comment by scloo** [comment]
Related to issue#19.

**Comment by gmcressman** [comment]
Tested. Fixed.
