### ISSUE TITLE
Household: Look-up on Shehia field appears to be broken.

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#26]
Tested in mobile.cococloud.co, democs, Chrome.

![screen shot 2017-12-21 at 4 06 33 pm](https://user-images.githubusercontent.com/329768/34275008-5f46b61a-e669-11e7-83c1-4f9c6aff7276.png)

**Comment by scloo** [comment]
This is now fixed. It is showing the lookup now.

**Comment by scloo** [comment]
Humphrey brought up the issue that the app reported invalid Shehia error message when user type in the Shehia name. When I checked the Shehia list, it is there.

**Comment by scloo** [comment]
Issue was that the user is typing in the Shehia in lowercase with captalization and the Shehia names in  list are all in Caps. Updated the validation script in questions to convert input to uppercase before validation.
