### ISSUE TITLE
democs, synch, prompts to accept many new records

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#27]
1. Installed democs on cococloud.co
2. Clicked on sync icon to sync data.
3. Received many, many prompts to accept transfer of a new case. These cases were not transferred. Why does the app think they have been transferred?
4. Acceptance dialog not in correct MD style. This should be styled correctly in MD.
5. Some records that I accepted were dated in the future. Why? This must have something to do with the demo data.
6. After accepting the new records, I had 121 new case notifications. The "home" summary display reported a total of 100 cases on the device. Why are these two numbers different?

![screen shot 2018-01-30 at 3 19 52 pm](https://user-images.githubusercontent.com/329768/35590869-1f3c3e96-05d6-11e8-8956-98531b08c953.png)

**Comment by scloo** [comment]
According to Mike, this is part of Coconut. It should only be offering you a case to accept if your user has a district that has new cases. Some record dated somewhere in the future is due to the demo data, which was generated by the anonymize script. Probably needs fine tuning to get the right range of dates.

**Comment by gmcressman** [comment]
Ah. My dim lightbulb just when on. Of course, for some reason the demo data contains new case notifications for the user/s (demomobile1) district. That's what we want, with two changes: (1) new case notifications should be recent (within the last 24 hours or so), not in the future, and (2) we probably only need 3-4 new case notifications in the same district as demomobile1, and 3-4 in the same district as demomobile2.

It would be nice to style that dialog with MD. Otherwise it looks good to me.
