### ISSUE TITLE
Household Member: Overnight Travel within Zanzibar between... should be marked as required field.

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#29]
![screen shot 2018-01-30 at 3 27 18 pm](https://user-images.githubusercontent.com/329768/35591248-4a764fec-05d7-11e8-8bb8-5b27c86e6438.png)

**Comment by scloo** [comment]
How did you get the "Overnight travel within Zanzibar..." to show up? I don't see it when I enter Household Member question.
![Screen Shot 2018-01-30 at 4.37.50 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571a5f9b500b7b0e00eca657/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226457f36b7191a37cf1112c4f5a5f5ecc3c4a4356bcbbd671f3e57862804e0eead06a0a71c33a17ffee8a18ed52e8208b4d86e0b98349d2f42f67b6d5db1063474f4dcbed5727a19141c95df74ce2495da7153663e4742431.png)

**Comment by gmcressman** [comment]
For Malaria Test Result* select PF.

**Comment by scloo** [comment]
Issue fixed.
