### ISSUE TITLE
Data tables error when working offline

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#3]
Working offline on ASUS ZenTab 8.0.

1. Completed new Notification x 3
2. Completed Facility x 1
3. Completed Household x 1 with 3 residents
4. Completed new Notification
5. Number of incomplete facility records was not incremented, and I received the following error message.

![screenshot_20170608-131127](https://user-images.githubusercontent.com/329768/27601537-b9b977b6-5b3d-11e7-87a9-0eb9ed0115ce.jpg)

**Comment by scloo** [comment]
Adding the 'retrieve: true' option into DataTable initialization will help prevent reinitializing of DataTable when it already exist.

**Comment by gmcressman** [comment]
Closing. Reopen if this reappears.
