### ISSUE TITLE
Reduce UI scrolling on smaller displays

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#4]
We could remove some text to reduce the need to scroll vertically on smaller displays. Increasing the font size on the COMPLETE and INCOMPLETE tabs may make them move obvious to users and larger touch targets.

![image](https://user-images.githubusercontent.com/329768/27736461-4c8c7f08-5d72-11e7-9f40-7dcc7de75334.png)

**Comment by scloo** [comment]
Changes implemented.
