### ISSUE TITLE
Question text cut off on narrow displays

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#5]
The text of long questions can be cut off on narrow screen displays.

![image](https://user-images.githubusercontent.com/329768/27752233-e8fae524-5dad-11e7-97c0-8fee59e77cca.png)
![image](https://user-images.githubusercontent.com/329768/27753867-7d6cd5f8-5db5-11e7-94d7-0f18abc762d5.png)

**Comment by gmcressman** [comment]
Not sure whether this should be in the coconut-mobile repo or here in this plug-in.

**Comment by scloo** [comment]
Duplicated issue as #9. Fixed.
