### ISSUE TITLE
Household : Locations questions repeated 5 times

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-mobile-plugin-zanzibar#9]
On the Household question set, after this question:

Index case: Overnight Travel outside Zanzibar in the past year?

The app displays "All locations..." 5 times. See example below. Is this by design?

![image](https://user-images.githubusercontent.com/329768/27753423-80065e94-5db3-11e7-9343-5c8cadf31424.png)

**Comment by scloo** [comment]
The 5 locations are each different, one for each 0-7 days, 8-14 days, 15-21 days, 22-42 days and 43-365 days. The words have been cut off in the mobile device. Will work on adjusting the width for the labels.

**Comment by scloo** [comment]
Fixed the truncated issue. The line is now being displayed on multiple lines.
